version: "3.8"

services:
  back:
    restart: always
    build:
      context: .
    env_file:
      - .env
    ports:
      - 4000:4000
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start

networks:
  default:
    external:
      name: restaurant-finder
